app = "app-expyoyej"
primary_region = "nrt"

[env]
  ENVIRONMENT = "production"
  CORS_ORIGINS = '["http://localhost:5173", "https://app-expyoyej.fly.dev"]'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
